<?xml version="1.0" encoding="utf-8"?><Database Name="Przychodnia" Class="PrzychodniaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=Przychodnia;Integrated Security=True" SettingsObjectName="DataLayer.Properties.Settings" SettingsPropertyName="PrzychodniaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Badanie_lab" Member="Badanie_labs">
    <Type Name="Badanie_lab">
      <Column Name="id_bad_lab" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="data_zlecenia" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="data_wyk_bad" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="data_zatw_bad" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="opis" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="wynik" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="uwagi_klab" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="stan" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="id_wizyty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_lab" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_klab" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lab_Badanie_lab" Member="Lab" ThisKey="id_lab" OtherKey="id_lab" Type="Lab" IsForeignKey="true" />
      <Association Name="K_Lab_Badanie_lab" Member="K_Lab" ThisKey="id_klab" OtherKey="id_klab" Type="K_Lab" IsForeignKey="true" />
      <Association Name="Slownik_badan_Badanie_lab" Member="Slownik_badan" ThisKey="wynik" OtherKey="kod" Type="Slownik_badan" IsForeignKey="true" />
      <Association Name="Wizyta_Badanie_lab" Member="Wizyta" ThisKey="id_wizyty" OtherKey="id_wizyty" Type="Wizyta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Badanie_fizykalne" Member="Badanie_fizykalnes">
    <Type Name="Badanie_fizykalne">
      <Column Name="id_bad_fiz" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="data_wykonania" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="wynik" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_wizyty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Slownik_badan_Badanie_fizykalne" Member="Slownik_badan" ThisKey="wynik" OtherKey="kod" Type="Slownik_badan" IsForeignKey="true" />
      <Association Name="Wizyta_Badanie_fizykalne" Member="Wizyta" ThisKey="id_wizyty" OtherKey="id_wizyty" Type="Wizyta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lab" Member="Labs">
    <Type Name="Lab">
      <Column Name="id_lab" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Lab_Badanie_lab" Member="Badanie_labs" ThisKey="id_lab" OtherKey="id_lab" Type="Badanie_lab" />
      <Association Name="User_Lab" Member="User" ThisKey="user_name" OtherKey="user_name" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.K_Lab" Member="K_Labs">
    <Type Name="K_Lab">
      <Column Name="id_klab" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="K_Lab_Badanie_lab" Member="Badanie_labs" ThisKey="id_klab" OtherKey="id_klab" Type="Badanie_lab" />
      <Association Name="User_K_Lab" Member="User" ThisKey="user_name" OtherKey="user_name" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lekarz" Member="Lekarzs">
    <Type Name="Lekarz">
      <Column Name="id_lekarza" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nr_uprawnienia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Lekarz_Wizyta" Member="Wizytas" ThisKey="id_lekarza" OtherKey="id_lekarza" Type="Wizyta" />
      <Association Name="User_Lekarz" Member="User" ThisKey="user_name" OtherKey="user_name" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pacjent" Member="Pacjents">
    <Type Name="Pacjent">
      <Column Name="id_pac" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nazwisko" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="imie" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PESEL" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Association Name="Pacjent_Wizyta" Member="Wizytas" ThisKey="id_pac" OtherKey="id_pac" Type="Wizyta" />
    </Type>
  </Table>
  <Table Name="dbo.Slownik_badan" Member="Slownik_badans">
    <Type Name="Slownik_badan">
      <Column Name="kod" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="typ" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="opis" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Slownik_badan_Badanie_lab" Member="Badanie_labs" ThisKey="kod" OtherKey="wynik" Type="Badanie_lab" />
      <Association Name="Slownik_badan_Badanie_fizykalne" Member="Badanie_fizykalnes" ThisKey="kod" OtherKey="wynik" Type="Badanie_fizykalne" />
    </Type>
  </Table>
  <Table Name="dbo.Rejestracja" Member="Rejestracjas">
    <Type Name="Rejestracja">
      <Column Name="id_rej" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Rejestracja_Wizyta" Member="Wizytas" ThisKey="id_rej" OtherKey="id_rej" Type="Wizyta" />
      <Association Name="User_Rejestracja" Member="User" ThisKey="user_name" OtherKey="user_name" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="user_name" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="data_konc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="nazwisko" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="imie" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="User_Lab" Member="Labs" ThisKey="user_name" OtherKey="user_name" Type="Lab" />
      <Association Name="User_K_Lab" Member="K_Labs" ThisKey="user_name" OtherKey="user_name" Type="K_Lab" />
      <Association Name="User_Lekarz" Member="Lekarzs" ThisKey="user_name" OtherKey="user_name" Type="Lekarz" />
      <Association Name="User_Rejestracja" Member="Rejestracjas" ThisKey="user_name" OtherKey="user_name" Type="Rejestracja" />
    </Type>
  </Table>
  <Table Name="dbo.Wizyta" Member="Wizytas">
    <Type Name="Wizyta">
      <Column Name="id_wizyty" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="opis" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="diagnoza" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="stan" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="data_rej" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="data_wyk_wizyty" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_pac" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_rej" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_lekarza" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Wizyta_Badanie_lab" Member="Badanie_labs" ThisKey="id_wizyty" OtherKey="id_wizyty" Type="Badanie_lab" />
      <Association Name="Wizyta_Badanie_fizykalne" Member="Badanie_fizykalnes" ThisKey="id_wizyty" OtherKey="id_wizyty" Type="Badanie_fizykalne" />
      <Association Name="Lekarz_Wizyta" Member="Lekarz" ThisKey="id_lekarza" OtherKey="id_lekarza" Type="Lekarz" IsForeignKey="true" />
      <Association Name="Pacjent_Wizyta" Member="Pacjent" ThisKey="id_pac" OtherKey="id_pac" Type="Pacjent" IsForeignKey="true" />
      <Association Name="Rejestracja_Wizyta" Member="Rejestracja" ThisKey="id_rej" OtherKey="id_rej" Type="Rejestracja" IsForeignKey="true" />
    </Type>
  </Table>
</Database>